### ISSUE TITLE
Incrementing a key whose value is not a number crashes the database

### ISSUE THREAD

**Issue by stormasm** [drbh/zedis#1]
set animal dog
inc animal

**Comment by drbh** [comment]
Thanks for pointing this bug out. Fixed immediately 

```rust
zedis >> set animal dog
// done
zedis >> inc animal
// Error occurred: NonIntValue
```

Now theres a **NonIntValue** error if you try to increment a value that is not an int. If this error is thrown the value is not changed.

This solves the above issue - please let me know if the fix is not working as expected 


see commits: https://github.com/drbh/zedis/commit/c5356a258aa689881ac590f1cda010aa2a2a6dea and https://github.com/drbh/zedis/commit/8b010840c2d57de5cfb1daff91cefa910e74664d if interested in the fix

**Comment by stormasm** [comment]
@drbh Wow, that was fast !  Thanks so much for fixing the bug and turning it around so quickly.  I updated the code and tested it as well --- very nice...
